### ISSUE TITLE
Did you run it on a couple of samples from ImageNet val? 

### ISSUE THREAD

**Issue by sayakpaul** [gatheluck/FourierHeatmap#2]
Hi. 

Thanks for open-sourcing this even before the authors could open-source their code. I was wondering if you were able to run your implementation on ImageNet val? If so, how does your setup look like?

**Comment by gatheluck** [comment]
Thank you for asking and sorry for my late reply.

Theoretically, it should work on ImageNet too, although I haven't run the calculations all the way through due to computational resource issue. In v0.2.0, you should be able to run the same experiment as in the original paper with the following code.

```
poetry run python fhmap/apps/eval_fhmap.py dataset=imagenet arch=resnet50 weightpath=[PYTORCH_MODEL_WEIGHT_PATH] eps=15.7
```

**Comment by sayakpaul** [comment]
No problem. Thank you for your great work!
